version: "3.7"
services:
  app:
    build:
      args:
        user: ayobami
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: aydev123/laravel
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist
  
  nginx:
    image: nginx:alpine
    container_name: ngnixlaravel
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travellist

networks:
  travellist:
    driver: bridge
