name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build app image
      run: docker-compose build app
    - name: Deploy to Docker Hub
      run: docker push aydev123/laravel
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ -d "laravel-app" ]; then
            rm -rf "laravel-app"
          fi
          git clone https://github.com/Ayobami-ANDROID/laravel-app.git
          cd "laravel-app"
          sudo docker rm -f laravel || true
          sudo docker rm -f ngnixlaravel || true
          sudo docker compose up -d
          sudo docker compose exec app composer install
          sudo docker compose exec app php artisan key:generate
